In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
def Vec (x, y, z):
    v = np.array ([[x], [y], [z]])
    return v.astype (float)

Gerade

Ein fester Punkt auf der Geraden

In [3]:
p = Vec (1, 0, 2)
p

array([[1.],
       [0.],
       [2.]])

Richtungsvektor

In [4]:
u = Vec (1, 2, 1)
u

array([[1.],
       [2.],
       [1.]])

Ebene

Ein fester Punkt auf der Ebene

In [5]:
q = Vec (2, 3, 1)
q

array([[2.],
       [3.],
       [1.]])

Erster Richtungsvektor

In [6]:
v = np.array ([
    [4],
    [2],
    [9]
])

Zweiter Richtungsvektor

In [7]:
w = np.array ([
    [3],
    [1],
    [6]
])

Gleichungssystem aufstellen und lösen

In [8]:
A = np.hstack ((u, -v, -w))
A

array([[ 1., -4., -3.],
       [ 2., -2., -1.],
       [ 1., -9., -6.]])

In [9]:
b = q - p
b

array([[ 1.],
       [ 3.],
       [-1.]])

In [10]:
x = la.solve (A, b)
x

array([[ 2.],
       [ 1.],
       [-1.]])

Probe

In [11]:
[[r], [s], [t]] = x
print (r, s, t)

2.0 1.0 -1.0


In [12]:
p + r * u

array([[3.],
       [4.],
       [4.]])

In [13]:
q + s * v + t * w

array([[3.],
       [4.],
       [4.]])