In [1]:
import numpy as np
import numpy.linalg as la

1. Gerade

Ein fester Punkt auf der Geraden

In [2]:
p = np.array ([
    [-3],
    [ 2]
])

Richtungsvektor

In [3]:
u = np.array ([
    [2],
    [2]
])

2. Gerade

Ein fester Punkt auf der Geraden

In [4]:
q = np.array ([
    [4],
    [3]
])

Richtungsvektor

In [5]:
v = np.array ([
    [ 1],
    [-2]
])

Gleichungssystem aufstellen und lösen

In [6]:
A = np.hstack ((u, -v))
A

array([[ 2, -1],
       [ 2,  2]])

In [7]:
b = q - p
b

array([[7],
       [1]])

In [8]:
x = la.solve (A, b)
x

array([[ 2.5],
       [-2. ]])

Probe

In [9]:
[[s], [t]] = x
print (s, t)

2.5 -2.0


In [10]:
p + s * u

array([[2.],
       [7.]])

In [11]:
q + t * v

array([[2.],
       [7.]])